### ISSUE TITLE
kinematic_helper: Multiple rotation directions

### ISSUE THREAD

**Issue by alpakadev** [alpakadev/robot-ludens#23]
The current `get_kinematic_move()` method alows a rotation along just one axis!
E.g:

```python
target_kinematic = self.kinematic_model_helper.get_kinematic_move(pose=pos_to, rot_direction='y', rot_axis=-90)
```

But we will need to create rotation matrices with rotations from all directions
E.g.: Desired (x,y,z)-rotaton: (10,-60,-45)
Please change code from `_build_rot_mat()` accordingly!
Am I missing something @louisborn?

https://github.com/alpakadev/robot-ludens/blob/0d6be9ac2c63b39caf4f9a325f916cea536009ed/PythonScripts/Movement/Helper/KinematicModelHelper.py#L31-L33

**Comment by louisborn** [comment]
_move_arm() method has new input argument 'rotation':

`def _move_arm(self, pos_to: list, rotation: dict):`

A rotation should have the following structure:

`{'y': -90, 'x': 0, 'z': -90}` -> a dict with key: string and value: int


Now every movement can have individual rotations depdening on the need of rotation to reach a certain pose

**Comment by alpakadev** [comment]
@louisborn, Did you perform a force push on your commits? 
If so, please remember to fetch first and create a new branch for the issue in the future.

**Comment by louisborn** [comment]
> @louisborn, Did you perform a force push on your commits? 
> If so, please remember to fetch first and create a new branch for the issue in the future.

There is a new branch see 23-multiple-rotation-directions

**Comment by alpakadev** [comment]
> There is a new branch see 23-multiple-rotation-directions

However, the dev branch was unexpectedly modified. - I'll try to resolve this issue

**Comment by alpakadev** [comment]
Is resolved now👍🏼
