### ISSUE TITLE
Turning Hand Rotation based on coordinates

### ISSUE THREAD

**Issue by alpakadev** [alpakadev/robot-ludens#32]
Issue #23 - Should be fixed first. - But this can be started concurrently assuming a working `_build_rot_mat()`

Based on the `x` and `y` coordinates, the Hand should be turned. 
Keep the function equation simple!

1. Write a Function to create a rotation in (at least) z-axies based on x, y
2. Let that function be called and used by `_move_arm()`
3. Test it in the virtual enviroment

## Visual representation

Here is a Visual representation on what we need

### Current Outcome

![Undesired-Hand-Rotation (Small)](https://github.com/alpakadev/robot-ludens/assets/64690504/b86106e5-eb67-4921-b348-c8dd2e950edc)

### Desired Outcome

![Desired-Hand-Rotation (Small)](https://github.com/alpakadev/robot-ludens/assets/64690504/a7c9ed65-fd17-4941-8010-c8a19a55439c)

**Comment by alpakadev** [comment]
Function `_move_arm()` has been updated:
https://github.com/alpakadev/robot-ludens/issues/23#issuecomment-1546636812

**Comment by louisborn** [comment]
early possible fix for hand rotation based on target pose using board enum. Should think about refactoring the main move_object method

**Comment by alpakadev** [comment]
@louisborn, How would you plan to refactor the move_object() method?
