### ISSUE TITLE
Interaction-Animation-Win-Loose

### ISSUE THREAD

**Issue by alpakadev** [alpakadev/robot-ludens#41]
Aus dem Discord:
Win: Arme angewinkelt hoch/runter und Antennen wackeln (Freude/Jubel)

Loose: Spieler anschauen, Runterschauen auf das Brett, Antennen hängen lassen (Enttäuschung)

der Funktionsaufruf muss dann von @Spielstrategie eingefügt werden

**Comment by KatjanNA** [comment]
temporary interaction movments have been added in MoveImpl.py, @louisborn be free to change stuff up like anm_win...or perhaps do the angry emot

**Comment by louisborn** [comment]
will have a look at it now

**Comment by louisborn** [comment]
I have added an extra Animations directory where all the animations are located. Added a "do_animation" method inside the facade which receives an Animation enum. In moveImpl we perform a match/case statement and call the required animation from the Animations directory.

**Comment by louisborn** [comment]
Win and loose animation is successfully tested @alpakadev

**Comment by KatjanNA** [comment]
good news: I merged main into 41-Interaction-Animation-Win-Loose.
Bad news: I didnt fix the conflicts, well...I tried to do so but I got confused by the different import ways in the files, better keep my hands off.

**Comment by alpakadev** [comment]
First off: No worries, merge conflicts always seem a bit scary😰
Here is a helpfull [Video](https://www.youtube.com/watch?v=HosPml1qkrg) about resolving merge conflicts.

Second off: From here on forward, remember to not commit an unresolved merge😄

@louisborn can you take care of the merge conflicts?

**Comment by louisborn** [comment]
I will have a look at it later
