### ISSUE TITLE
Hand glitching through Object when trying to Hold

### ISSUE THREAD

**Issue by alpakadev** [alpakadev/robot-ludens#5]
Most of the Time, when closing the gripper, the Hand glitches through the object.
Suggestion: Work on Rigidbody and Collider of Objects

**Comment by michalitv21** [comment]
If the hand is quite close to an object with its stiff part, holding the zylinders works well.

https://user-images.githubusercontent.com/130777255/235349994-43229597-92c9-4d68-8c59-1e27999d6ccb.mp4
