### ISSUE TITLE
Improve Movement

### ISSUE THREAD

**Issue by alpakadev** [alpakadev/robot-ludens#67]
# Improve Movement

The arm movements definitely need to be improved.

## The issues

Related to #43 

1. Objects are not always gripped securely.
2. When laying down on a surface, other blocks may be in the way. Reachy applies excessive force in those situations.
3. Make the movements more natural. For example, the arm doesn't always need to be brought to a right angle at the beginning.

## ToDo

I expect an adjustment of the current function or the implementation of new functions, such as grabbing from above. 👍 The mentioned issues need to be addressed.

You have time until the meeting on Friday.⏲️ (Thursday would be great, of course.)

## Suggestions for possible solutions

1. Using different angles (i.e. always 65^) when putting Items down as suggested by @louisborn, preventing having other blocks under the Hand.
2. Grabbing blocks from above like a crane
3. Dropping blocks from above to not even putting the hand down

**Comment by GalaxyLPS** [comment]
Are issues 1. and 2. reproducible in unity? @alpakadev

**Comment by alpakadev** [comment]
The First one, not quiet. Unity gives an idea about the physics but its better to test with the real Reachy on that.

The second one should be easy enough to reproduce. Just move the Blocks in the first line of fields and let reachy try to move the next block on the fields "behind" the filled fields. The hand will hit them from above with our current movement
