### ISSUE TITLE
Global function for turn on/off reachy

### ISSUE THREAD

**Issue by louisborn** [alpakadev/robot-ludens#69]
Create a global method to handle the turn on/off of reachy (arms, head, etc.)

Problem:
Multiple turn on/off statements we can not control if reachy parts drop on table
No single instance where we control the reachy 

Solution:
Create method that manages the turn on/off + add goto where reachys arms are put into safe position, e.g.: base position where turning off is safe

Use this function where needed

@alpakadev opinion?

**Comment by alpakadev** [comment]
> Solution:
> Create method that manages the turn on/off + add goto where reachys arms are put into safe position, e.g.: base position where turning off is safe
> 
> Use this function where needed

Seems like a good Idea. Just need positions outside of the board to drop the arms and not accidentally move Objects.

Currently we do have the functions: `activate_right_arm()` and `deactivate_right_arm()`. They are rarely used yet.
