### ISSUE TITLE
Animation look at

### ISSUE THREAD

**Issue by alpakadev** [alpakadev/robot-ludens#71]
There is always the same Error with:

Here the win animation as an example
`Head.look_at() missing 2 required positional arguments: 'y' and 'z' `

https://github.com/alpakadev/robot-ludens/blob/171da8b21276a476c0db8bd5b995bf456a5faf97/PythonScripts/Movement/Animations/Win.py#L13-L15

Should be more like this:

https://github.com/alpakadev/robot-ludens/blob/171da8b21276a476c0db8bd5b995bf456a5faf97/PythonScripts/Movement/MoveImpl.py#L221-L223

**Comment by KatjanNA** [comment]
should be fixed now, imports of do_head_move or move_head would lead to error due to circular import. Thus, back to using reachy.head.look_at()
