### ISSUE TITLE
Animation Thinking - Almost hits head

### ISSUE THREAD

**Issue by alpakadev** [alpakadev/robot-ludens#72]
Bring the head in a save Position before moving the arm infront of the head.
It seems like Reachy is almost hitting its head

**Comment by KatjanNA** [comment]
I will remove this animation for good.

**Comment by alpakadev** [comment]
@KatjanNA Why removing it?🤔 It is actually cool. 😄 
Also the head seems to be moved to a save position.👍🏼 (I think I just missed that, when I skimmed the code)

Perhaps consider slowing down the initial/first movement. (`duration`)
(Since it is a long way from Table to the head.)
It had me scared for a second. 

https://github.com/alpakadev/robot-ludens/blob/9d02c2c5150d81d22eb2ab9fa4ea0a8ae9e6d39c/PythonScripts/Movement/Animations/Thinking.py#L24-L28

Consider slowing down all the initial movements for the other animations as well, given the occasional twitching of the robot.

Since you've submitted two pull requests—one including the Thinking animation and the other without it—I assume that you've given me the freedom to make the choice.😄

For now, I will merge the pull request that includes the thinking animation.
If you still want it removed, thats no problem
