### ISSUE TITLE
Close Gripper until is_holding

### ISSUE THREAD

**Issue by alpakadev** [alpakadev/robot-ludens#8]
As of now, there is a predefined closing position. 
But It should be continuously closed until is_holding is met!

**Comment by alpakadev** [comment]
Use `_change_grip_force(force)` and `is_holding` for this

But there is one problem with `is_holding`: `reachy.force_sensors.r_force_gripper.force` is always ridiculously large!
Look up the appropriate Docs for reachy from Pollen Robotics

**Comment by louisborn** [comment]
see branch "8-close-gripper-until-isHolding"

**Comment by louisborn** [comment]
also added time check to abort loop after 5 seconds passed. can be increased/ decreased if wanted

**Comment by alpakadev** [comment]
Cannot be resolved for now
