### ISSUE TITLE
Main Zeile 33-35 auslagern

### ISSUE THREAD

**Issue by GalaxyLPS** [alpakadev/robot-ludens#80]
Bewegung Verbessern; schneller und Präziser machen. Main Zeile 33-35 auslagern

https://trello.com/c/syljND5u

**Comment by GalaxyLPS** [comment]
Sollen hier die Zeilen 34, 35 und 36 ausgelagert werden oder wirklich nur die Zeilen 34 und 45? @alpakadev

**Comment by alpakadev** [comment]
Sorry, ich habe es vage ausgedrückt. Ich hatte keine Zeit, ein Issue zu erstellen, in denen ich es genauer erklärt hätte.

Mir geht's um diese folgenden Zeilen:

https://github.com/alpakadev/robot-ludens/blob/main/PythonScripts/main.py#L34-L36

Diese drei Funktionen sollen den Arm in eine sichere Ausgangsposition über den Blöcken bewegen, ohne etwas auf dem Weg umzuwerfen.

Ich möchte die main.py simpel halten. Daher sollten diese drei Funktionen besser in der MoveFacade aufgerufen werden. Sollte ja schnell gehen.

(Vergiss nicht, dass die Bewegung erst nach der Kalibrierung aufgerufen werden können. Also nicht direkt in die init Packen)

**Comment by GalaxyLPS** [comment]
Soll der PR in main gehen?
