### ISSUE TITLE
Movement of left arm

### ISSUE THREAD

**Issue by GalaxyLPS** [alpakadev/robot-ludens#82]
Implement movement of left arm to realize stealing pieces from the board

**Comment by GalaxyLPS** [comment]
Possible Problems:
- After stealing a piece, Reachy will detect an illegal state and act accordingly. We need Reachy to act like nothing happend/the Board is in a legal state

**Comment by GalaxyLPS** [comment]
Current solutions: We only move a block from left to center column. We will not reach an illegal state using this. We will only use the left arm to not be **that** obvious.

**Comment by GalaxyLPS** [comment]
![image](https://github.com/alpakadev/robot-ludens/assets/33934075/81bf831a-9f3b-4fb8-8c45-18248664a258)

Giving reachy values of [0, -0.1, 0] for both arms (calculating the kinematic, inversing it and applying it to the arms) results in completly fucked up positions. What the fuck

**Comment by GalaxyLPS** [comment]
![image](https://github.com/alpakadev/robot-ludens/assets/33934075/a11130d1-14aa-4031-ad59-d9d213926672)
and thats for [0, 0.1, 0]. Do we see a pattern here?

**Comment by GalaxyLPS** [comment]
![image](https://github.com/alpakadev/robot-ludens/assets/33934075/754734df-e415-49c7-9430-0488ca185feb)

taking a position from the game board, inverting its second field ([1]) and using this value for the left arm while using the normal for the right arm shows this...

**Comment by GalaxyLPS** [comment]
![image](https://github.com/alpakadev/robot-ludens/assets/33934075/b351753e-c062-4d02-9fea-ac74b432ed2e)
playing around with rotation, we have this

**Comment by alpakadev** [comment]
> and thats for [0, 0.1, 0]. Do we see a pattern here?

### Firstly

Firstly, it is impossible for Reachy to reach those coordinates. 
You are attempting to move the **_Hand_** 10 cm to the left or right of Reachy's central point. 
The central point is in Reachy's chest (Pollen Robotics symbol.)
The shoulder itself is 20cm from the Central point away.

![10cm](https://github.com/alpakadev/robot-ludens/assets/64690504/f51af2a8-c0c5-4334-8c09-f22342d3753d)

So why even use these Coordinates?🤔

### Secondly

Secondly, when starting the game, do you have any problems with the movements?
If so, check your ReachySDK. 
For the Unity Environment we use reachy-sdk: 0.40; reachy_sdk_api: 0.4.5. (Only in Order the Headmovement to Work)
While the real Reachy requires the newest version. 



### Thirdly

If you have forgotten:
All the Coordinates stored in our Enums are saved relative to our `Origin` Point (Bottom right corner of Board).
Therefore In `move_object(...)` we add the `Origin` Point to the coordinates

https://github.com/alpakadev/robot-ludens/blob/94c93853e875f6592bd91f98f8ce027173ba2221/PythonScripts/Movement/MoveImpl.py#L90-L93
