### ISSUE TITLE
reachy happy antennas

### ISSUE THREAD

**Issue by louisborn** [alpakadev/robot-ludens#83]
Reachy happy antennas animation is not working with reachy in UDE Lab.

video: https://drive.google.com/file/d/1NqtPNDbm5LwmsiB695Kn7OZRHDO9FhZp/view?usp=sharing

The happy antennas is working fine in unity env.

Code used:
`import time

def animation_happy_antennas(reachy):
    reachy.head.l_antenna.speed_limit = 0.0
    reachy.head.r_antenna.speed_limit = 0.0

    for _ in range(9):
        reachy.head.l_antenna.goal_position = 10.0
        reachy.head.r_antenna.goal_position = -10.0

        time.sleep(0.1)

        reachy.head.l_antenna.goal_position = -10.0
        reachy.head.r_antenna.goal_position = 10.0

    time.sleep(0.1)

    reachy.head.l_antenna.goal_position = 0.0
    reachy.head.r_antenna.goal_position = 0.0
`

**Comment by KatjanNA** [comment]
seems to be a mechnical issue, not a coding one...I added a alternative happy animation for interaction
